# https://github.blog/2023-07-11-github-cli-project-command-is-now-generally-available/
name: projs_cleanup

on:
    workflow_dispatch:

jobs:
    close_empty:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        steps:
            - name: Get project list
              run: |
                  projects=$(gh project list --owner @me --format=json)
                  if [[ -z "$projects" ]]; then
                    echo "No projects found"
                    exit 0
                  fi
            - name: Close empty projects
              run: |
                  gh project list --owner @me --format=json | jq '.projects[] | select(.items.totalCount == 0) | .number' | xargs -n1 -I % gh project close % --owner @me
